#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-simplejson
Version  : 3.13.2
Release  : 58
URL      : https://github.com/simplejson/simplejson/archive/v3.13.2.tar.gz
Source0  : https://github.com/simplejson/simplejson/archive/v3.13.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : AFL-2.1
Requires: deprecated-simplejson-license = %{version}-%{release}
Requires: deprecated-simplejson-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : py
BuildRequires : pytest

%description
simplejson
----------
.. image:: https://travis-ci.org/simplejson/simplejson.svg?branch=master
:target: https://travis-ci.org/simplejson/simplejson

%package legacypython
Summary: legacypython components for the deprecated-simplejson package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-simplejson package.


%package license
Summary: license components for the deprecated-simplejson package.
Group: Default

%description license
license components for the deprecated-simplejson package.


%package python
Summary: python components for the deprecated-simplejson package.
Group: Default

%description python
python components for the deprecated-simplejson package.


%prep
%setup -q -n simplejson-3.13.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554328462
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python2.7/site-packages python setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-simplejson
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/deprecated-simplejson/LICENSE.txt
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-simplejson/LICENSE.txt

%files python
%defattr(-,root,root,-)
